// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using SqlPlus.Data.Models;

namespace SqlPlus.Data
{
    public partial class Service
    {

        /// <summary>
        /// Builds the command object for FeedbackTopCount method.
        /// </summary>
        /// <param name="cnn">The connection that will execute the procedure.</param>
        /// <param name="input">FeedbackTopCountInput instance for loading parameter values.</param>
        /// <returns>SqlCommand ready for execution.</returns>
        private SqlCommand GetFeedbackTopCountCommand(SqlConnection cnn, IFeedbackTopCountInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.Text,
                CommandText = "SELECT * FROM [dbo].[FeedbackTopCount](@Count)",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@Count",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
				Value = (object)input.Count ?? DBNull.Value
            });

            return result;
        }

        private FeedbackTopCountResult GetFeedbackTopCountResultFromReader(SqlDataReader rdr)
        {
            FeedbackTopCountResult result = new FeedbackTopCountResult();

            result.FeedbackId = rdr.GetInt32(0);

            result.LastName = rdr.GetString(1);

            result.FirstName = rdr.GetString(2);

            result.Email = rdr.GetString(3);

            result.Subject = rdr.GetString(4);

            result.Message = rdr.GetString(5);

            result.Created = rdr.GetDateTime(6);

            return result;
        }


        private void FeedbackTopCountCommand(SqlCommand cmd, FeedbackTopCountOutput output)
        {
            using (SqlDataReader rdr = cmd.ExecuteReader())
            {
                output.ResultData = new List<FeedbackTopCountResult>();
                while(rdr.Read())
                {
                    output.ResultData.Add(GetFeedbackTopCountResultFromReader(rdr));
                }
                rdr.Close();
            }
        }

        /// <summary>
        /// Comment
        /// SQL+ Routine: dbo.FeedbackTopCount - Authored by Author
        /// </summary>
        public FeedbackTopCountOutput FeedbackTopCount(IFeedbackTopCountInput input, bool bypassValidation = false)
        {
            if(!bypassValidation)
            {
                if (!input.IsValid())
                {
		            throw new ArgumentException("FeedbackTopCountInput fails validation - use the FeedbackTopCountInput.IsValid() method prior to passing the input argument to the FeedbackTopCount method.", "input");
                }
            }
            FeedbackTopCountOutput output = new FeedbackTopCountOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetFeedbackTopCountCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    FeedbackTopCountCommand(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if(idx > 0)
                {
                    System.Threading.Thread.Sleep(retryOptions.RetryIntervals[idx-1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetFeedbackTopCountCommand(cnn, input))
                    {
                        cnn.Open();
						FeedbackTopCountCommand(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    bool throwException = true;

                    if(retryOptions.TransientErrorNumbers.Contains(sqlException.Number))
                    {
                        throwException = (idx == retryOptions.RetryIntervals.Count);

                        if (retryOptions.Logger != null)
                        {
                            retryOptions.Logger.Log(sqlException);
                        }
                    }
                    if(throwException)
                    {
                        throw;
                    }
                }
            }
            return output;
        }
    }
}