// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using SqlPlus.Data.Models;

namespace SqlPlus.Data
{
    public partial class Service
    {

        /// <summary>
        /// Builds the command object for GetSQLDateTime method
        /// </summary>
        /// <param name="cnn">The connection that will execute the procedure</param>
        /// <returns>SqlCommand ready for execution</returns>
        private SqlCommand GetGetSQLDateTimeCommand(SqlConnection cnn)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "[dbo].[GetSQLDateTime]",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.DateTime,
                Precision = 3,
                Value = DBNull.Value
            });

            return result;
        }
        private void SetGetSQLDateTimeCommandOutputs(SqlCommand cmd, GetSQLDateTimeOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (DateTime?)cmd.Parameters[0].Value;
            }
        }
        private void GetSQLDateTimeCommand(SqlCommand cmd, GetSQLDateTimeOutput output)
        {
            cmd.ExecuteNonQuery();
            SetGetSQLDateTimeCommandOutputs(cmd, output);
        }

        /// <summary>
        /// Gets the current time from the server
        /// SQL+ Routine: dbo.GetSQLDateTime - Authored by Alan Hyneman
        /// </summary>
        public GetSQLDateTimeOutput GetSQLDateTime()
        {
            GetSQLDateTimeOutput output = new GetSQLDateTimeOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetGetSQLDateTimeCommand(sqlConnection))
                {
                    cmd.Transaction = sqlTransaction;
                    GetSQLDateTimeCommand(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if(idx > 0)
                {
                    System.Threading.Thread.Sleep(retryOptions.RetryIntervals[idx-1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetGetSQLDateTimeCommand(cnn))
                    {
                        cnn.Open();
						GetSQLDateTimeCommand(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    bool throwException = true;

                    if(retryOptions.TransientErrorNumbers.Contains(sqlException.Number))
                    {
                        throwException = (idx == retryOptions.RetryIntervals.Count);

                        if (retryOptions.Logger != null)
                        {
                            retryOptions.Logger.Log(sqlException);
                        }
                    }
                    if(throwException)
                    {
                        throw;
                    }
                }
            }
            return output;
        }
    }
}