// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SqlPlus.Data.Default.Models
{
    /// <summary>
    /// Output object for FeedbackDelete method.
    /// </summary>
    public class FeedbackDeleteOutput
    {
        public enum Returns
        {
             NotFound = 0,
             Deleted = 1
        }

		public Returns ReturnValue { set; get; }

    }
}