// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SqlPlus.Data.Default.Models
{
    /// <summary>
    /// Interface for FeedbackUpsertInput object.
    /// </summary>
    public interface IFeedbackUpsertInput : IValidInput
    {
        int? FeedbackId { set; get; }
        string LastName { set; get; }
        string FirstName { set; get; }
        string Email { set; get; }
        string Subject { set; get; }
        string Message { set; get; }
    }

    /// <summary>
    /// Input object for FeedbackUpsert method.
    /// </summary>
    public class FeedbackUpsertInput : ValidInput, IFeedbackUpsertInput
    {
        [Required(AllowEmptyStrings = false)]
        public int? FeedbackId { set; get; }  = (int?)0;

        [Display(Name = "Last Name", Description = "Last Name")]
        [MaxLength(32)]
        [Required(AllowEmptyStrings = false)]
        public string LastName { set; get; }

        [Display(Name = "First Name", Description = "First Name")]
        [MaxLength(32)]
        [Required(AllowEmptyStrings = false)]
        public string FirstName { set; get; }

        [EmailAddress]
        [DataType(DataType.EmailAddress)]
        [MaxLength(64)]
        [Required(AllowEmptyStrings = false)]
        public string Email { set; get; }

        [MaxLength(32)]
        [Required(AllowEmptyStrings = false)]
        public string Subject { set; get; }

        [MaxLength(1024)]
        [Required(AllowEmptyStrings = false)]
        public string Message { set; get; }

    }
} 