// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SqlPlus.Data.SampleNamespace.Models
{
    /// <summary>
    /// Interface for HelloWorldInput object.
    /// </summary>
    public interface IHelloWorldInput : IValidInput
    {
        string Name { set; get; }
    }

    /// <summary>
    /// Input object for HelloWorld method.
    /// </summary>
    public class HelloWorldInput : ValidInput, IHelloWorldInput
    {
        [MaxLength(32)]
        [Required(AllowEmptyStrings = false)]
        public string Name { set; get; }

    }
} 