// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SqlPlus.Data.Models
{
    /// <summary>
    /// Interface for FeedbackTableInput object.
    /// </summary>
    public interface IFeedbackTableInput : IValidInput
    {
        int? FeedbackId { set; get; }
    }

    /// <summary>
    /// Input object for FeedbackTable method.
    /// </summary>
    public class FeedbackTableInput : ValidInput, IFeedbackTableInput
    {
        [Required(AllowEmptyStrings = false)]
        public int? FeedbackId { set; get; }

    }
} 