// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SqlPlus.Data.Models
{
    /// <summary>
    /// Interface for FeedbackPagedInput object.
    /// </summary>
    public interface IFeedbackPagedInput : IValidInput
    {
        int? PageSize { set; get; }
        int? PageNumber { set; get; }
    }

    /// <summary>
    /// Input object for FeedbackPaged method.
    /// </summary>
    public class FeedbackPagedInput : ValidInput, IFeedbackPagedInput
    {
        [Range(typeof(int), "10", "50")]
        [Required(AllowEmptyStrings = false)]
        public int? PageSize { set; get; }  = (int?)25;

        [Required(AllowEmptyStrings = false)]
        public int? PageNumber { set; get; }  = (int?)1;

    }
} 