// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System.Collections.Generic;
namespace SqlPlus.Data.Models
{
    /// <summary>
    /// Result object for FeedbackTableMulti routine.
    /// </summary>
    public partial class FeedbackTableMultiResult
	{
        public int? FeedbackId { set; get; }
        public string LastName { set; get; }
    }
}