// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SqlPlus.Data.Models
{
    /// <summary>
    /// Interface for FeedbackTopCountInput object.
    /// </summary>
    public interface IFeedbackTopCountInput : IValidInput
    {
        int? Count { set; get; }
    }

    /// <summary>
    /// Input object for FeedbackTopCount method.
    /// </summary>
    public class FeedbackTopCountInput : ValidInput, IFeedbackTopCountInput
    {
        public int? Count { set; get; }

    }
} 