// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SqlPlus.Data.Models
{
    /// <summary>
    /// Output object for FeedbackTableMulti method.
    /// </summary>
    public partial class FeedbackTableMultiOutput
    {

        /// <summary>
        /// List of FeedbackTableMultiResult results.
        /// </summary>
        public List<FeedbackTableMultiResult> ResultData { set; get; }
    }
}