// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SqlPlus.Data.Models
{
    /// <summary>
    /// Interface for FeedbackTableMultiInput object.
    /// </summary>
    public interface IFeedbackTableMultiInput : IValidInput
    {
        int? FeedbackId { set; get; }
    }

    /// <summary>
    /// Input object for FeedbackTableMulti method.
    /// </summary>
    public class FeedbackTableMultiInput : ValidInput, IFeedbackTableMultiInput
    {
        public int? FeedbackId { set; get; }

    }
} 