// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SqlPlus.Data.Models
{
    /// <summary>
    /// Interface for FeedbackUpdateInput object.
    /// </summary>
    public interface IFeedbackUpdateInput : IValidInput
    {
        int? FeedbackId { set; get; }
        string LastName { set; get; }
        string FirstName { set; get; }
        string Email { set; get; }
        string Subject { set; get; }
        string Message { set; get; }
    }

    /// <summary>
    /// Input object for FeedbackUpdate method.
    /// </summary>
    public class FeedbackUpdateInput : ValidInput, IFeedbackUpdateInput
    {
        /// <summary>
        /// FeedbackId
        /// </summary>
        [Required(AllowEmptyStrings = false)]
        public int? FeedbackId { set; get; }

        /// <summary>
        /// LastName
        /// </summary>
        [MaxLength(32)]
        [Required(AllowEmptyStrings = false)]
        public string LastName { set; get; }

        /// <summary>
        /// FirstName
        /// </summary>
        [MaxLength(32)]
        [Required(AllowEmptyStrings = false)]
        public string FirstName { set; get; }

        /// <summary>
        /// Email
        /// </summary>
        [EmailAddress]
        [MaxLength(64)]
        [Required(AllowEmptyStrings = false)]
        public string Email { set; get; }

        /// <summary>
        /// Subject
        /// </summary>
        [MaxLength(32)]
        [Required(AllowEmptyStrings = false)]
        public string Subject { set; get; }

        /// <summary>
        /// Message
        /// </summary>
        [MaxLength(1024)]
        [Required(AllowEmptyStrings = false)]
        public string Message { set; get; }

    }
} 