// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using SqlPlus.Data.Default.Models;

namespace SqlPlus.Data.Default
{
    public partial class Service
    {

        /// <summary>
        /// Builds the command object for FeedbackDelete method.
        /// </summary>
        /// <param name="cnn">The connection that will execute the procedure.</param>
        /// <param name="input">FeedbackDeleteInput instance for loading parameter values.</param>
        /// <returns>SqlCommand ready for execution.</returns>
        private SqlCommand GetFeedbackDeleteCommand(SqlConnection cnn, IFeedbackDeleteInput input)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "dbo.FeedbackDelete",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@FeedbackId",
                Direction = ParameterDirection.Input,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
				Value = input.FeedbackId
            });

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            return result;
        }
        private void SetFeedbackDeleteCommandOutputs(SqlCommand cmd, FeedbackDeleteOutput output)
        {
            if(cmd.Parameters[1].Value != DBNull.Value)
            {
                output.ReturnValue = (FeedbackDeleteOutput.Returns)cmd.Parameters[1].Value;
            }
        }
        private void FeedbackDeleteCommand(SqlCommand cmd, FeedbackDeleteOutput output)
        {
            cmd.ExecuteNonQuery();
		
            SetFeedbackDeleteCommandOutputs(cmd, output);
		}

        /// <summary>
        /// Deletes single row from dbo.Feedback table by identity column.
        /// SQL+ Routine: dbo.FeedbackDelete - Authored by Alan Hyneman
        /// </summary>
        public FeedbackDeleteOutput FeedbackDelete(IFeedbackDeleteInput input)
        {
            if (!input.IsValid())
            {
		        throw new ArgumentException("FeedbackDeleteInput fails validation - use the FeedbackDeleteInput.IsValid() method prior to passing the input argument to the FeedbackDelete method.", "input");
            }
			
            FeedbackDeleteOutput output = new FeedbackDeleteOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetFeedbackDeleteCommand(sqlConnection, input))
                {
                    cmd.Transaction = sqlTransaction;
                    FeedbackDeleteCommand(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if(idx > 0)
                {
                    System.Threading.Thread.Sleep(retryOptions.RetryIntervals[idx-1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetFeedbackDeleteCommand(cnn, input))
                    {
                        cnn.Open();
						FeedbackDeleteCommand(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    bool throwException = true;

                    if(retryOptions.TransientErrorNumbers.Contains(sqlException.Number))
                    {
                        throwException = (idx == retryOptions.RetryIntervals.Count);

                        if (retryOptions.Logger != null)
                        {
                            retryOptions.Logger.Log(sqlException);
                        }
                    }
                    if(throwException)
                    {
                        throw;
                    }
                }
            }
            return output;
        }
    }
}