// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SqlPlusDemo.Data.dbo.Models
{
    /// <summary>
    /// Output object for HelloWorld method.
    /// </summary>
    public class HelloWorldOutput
    {

		public int? ReturnValue { set; get; }

    }
}