// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by SqlPlus.net
//     For more information on SqlPlus.net visit http://www.SqlPlus.net
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;
using SqlPlusDemo.Data.dbo.Models;

namespace SqlPlusDemo.Data.dbo
{
    public partial class Service
    {

        /// <summary>
        /// Builds the command object for HelloWorld method
        /// </summary>
        /// <param name="cnn">The connection that will execute the procedure</param>
        /// <returns>SqlCommand ready for execution</returns>
        private SqlCommand GetHelloWorldCommand(SqlConnection cnn)
        {
            SqlCommand result = new SqlCommand()
            {
                CommandType = CommandType.StoredProcedure,
                CommandText = "dbo.HelloWorld",
                Connection = cnn
            };

            result.Parameters.Add(new SqlParameter()
            {
                ParameterName = "@ReturnValue",
                Direction = ParameterDirection.ReturnValue,
                SqlDbType = SqlDbType.Int,
                Scale = 0,
                Precision = 10,
                Value = DBNull.Value
            });

            return result;
        }
        private void SetHelloWorldCommandOutputs(SqlCommand cmd, HelloWorldOutput output)
        {
            if(cmd.Parameters[0].Value != DBNull.Value)
            {
                output.ReturnValue = (int?)cmd.Parameters[0].Value;
            }
        }
        private void HelloWorldCommand(SqlCommand cmd, HelloWorldOutput output)
        {
            cmd.ExecuteNonQuery();
		
            SetHelloWorldCommandOutputs(cmd, output);
		}

        /// <summary>
        /// Comment
        /// SQL+ Routine: dbo.HelloWorld - Authored by Author
        /// </summary>
        public HelloWorldOutput HelloWorld()
        {
            HelloWorldOutput output = new HelloWorldOutput();
			if(sqlConnection != null)
            {
                using (SqlCommand cmd = GetHelloWorldCommand(sqlConnection))
                {
                    cmd.Transaction = sqlTransaction;
                    HelloWorldCommand(cmd, output);
                }
                return output;
            }
            for(int idx=0; idx <= retryOptions.RetryIntervals.Count; idx++)
            {
                if(idx > 0)
                {
                    System.Threading.Thread.Sleep(retryOptions.RetryIntervals[idx-1]);
                }
                try
                {
                    using (SqlConnection cnn = new SqlConnection(connectionString))
                    using (SqlCommand cmd = GetHelloWorldCommand(cnn))
                    {
                        cnn.Open();
						HelloWorldCommand(cmd, output);
                        cnn.Close();
                    }
					break;
                }
                catch(SqlException sqlException)
                {
                    bool throwException = true;

                    if(retryOptions.TransientErrorNumbers.Contains(sqlException.Number))
                    {
                        throwException = (idx == retryOptions.RetryIntervals.Count);

                        if (retryOptions.Logger != null)
                        {
                            retryOptions.Logger.Log(sqlException);
                        }
                    }
                    if(throwException)
                    {
                        throw;
                    }
                }
            }
            return output;
        }
    }
}